export const Tasks = [
  {
    id: 1,
    title: "Xterra",
    desc: "St. Petersburg State Mountain Institut",
    date: "10/27/2019",
  },
  {
    id: 2,
    title: "Passat",
    desc: "Dhaka International University",
    date: "09/15/2019",
  },
  {
    id: 3,
    title: "Range Rover",
    desc: "Universidade do Vale do Itajaí",
    date: "08/30/2019",
  },
  {
    id: 4,
    title: "Mustang",
    desc: "Fachhochschule Ingolstadt",
    date: "11/30/2019",
  },
  {
    id: 5,
    title: "Durango",
    desc: "Lagrange College",
    date: "12/21/2019",
  },
  {
    id: 6,
    title: "RL",
    desc: "United States Coast Guard Academy",
    date: "06/13/2019",
  },
  {
    id: 7,
    title: "LeBaron",
    desc: "Ecole Mohammadia d'Ingénieurs",
    date: "07/02/2019",
  },
  {
    id: 8,
    title: "Caravan",
    desc: "Fred Hutchinson Cancer Research Center",
    date: "07/26/2019",
  },
  {
    id: 9,
    title: "Sable",
    desc: "Kano State University of Technology Wudil",
    date: "12/03/2019",
  },
  {
    id: 10,
    title: "A7",
    desc: "Colorado Technical University",
    date: "10/20/2019",
  },
  {
    id: 11,
    title: "Dakota Club",
    desc: "Universidad de Palermo",
    date: "11/15/2019",
  },
  {
    id: 12,
    title: "S80",
    desc: "Instituto Tecnológico de Santo Domingo",
    date: "07/29/2019",
  },
  {
    id: 13,
    title: "5 Series",
    desc: "Yugra State University",
    date: "10/13/2019",
  },
  {
    id: 14,
    title: "SLK-Class",
    desc: "Fachhochschule für Bank- und Finanzwirtschaft",
    date: "03/22/2020",
  },
  {
    id: 15,
    title: "LX",
    desc: "Lviv National Medical Univeristy",
    date: "10/06/2019",
  },
  {
    id: 16,
    title: "Accent",
    desc: "Uganda Christian University",
    date: "01/25/2020",
  },
  {
    id: 17,
    title: "Aveo",
    desc: "Texas Woman's University",
    date: "01/29/2020",
  },
  {
    id: 18,
    title: "98",
    desc: "Universidade de Coimbra",
    date: "08/15/2019",
  },
  {
    id: 19,
    title: "Miata MX-5",
    desc: "Liszt Ferenc Academy of Music Budapest",
    date: "02/04/2020",
  },
  {
    id: 20,
    title: "Civic",
    desc: "Université Louis Pasteur (Strasbourg I)",
    date: "08/07/2019",
  },
  {
    id: 21,
    title: "Quest",
    desc: "Whittier College",
    date: "04/15/2020",
  },
  {
    id: 22,
    title: "Talon",
    desc: "Technological University (Pakokku)",
    date: "09/28/2019",
  },
  {
    id: 23,
    title: "Pathfinder",
    desc: "Universität Kaiserslautern",
    date: "12/16/2019",
  },
  {
    id: 24,
    title: "Club Wagon",
    desc: "Universidad Católica de Honduras",
    date: "02/18/2020",
  },
  {
    id: 25,
    title: "Savana 3500",
    desc: "Instituto Tecnológico de Buenos Aires",
    date: "11/19/2019",
  },
  {
    id: 26,
    title: "Silverado 1500",
    desc: "Université du Burundi",
    date: "08/13/2019",
  },
  {
    id: 27,
    title: "X5",
    desc: "Monash University",
    date: "12/31/2019",
  },
  {
    id: 28,
    title: "MX-5",
    desc: "Rajshahi University of Engineering and Technology",
    date: "10/16/2019",
  },
  {
    id: 29,
    title: "Continental",
    desc: "Universidad Católica del Norte",
    date: "09/23/2019",
  },
  {
    id: 30,
    title: "V12 Vantage",
    desc: "University of Science and Technology",
    date: "08/26/2019",
  },
  {
    id: 31,
    title: "Eclipse",
    desc: "Universitas Widyatama",
    date: "11/11/2019",
  },
  {
    id: 32,
    title: "Eclipse",
    desc: "Kazak State University of Agriculture",
    date: "09/05/2019",
  },
  {
    id: 33,
    title: "Civic",
    desc: "Gomal University",
    date: "03/06/2020",
  },
  {
    id: 34,
    title: "Monte Carlo",
    desc: "Concordia University",
    date: "08/16/2019",
  },
  {
    id: 35,
    title: "Malibu",
    desc: "Ecole Normale Supérieure de Cachan",
    date: "05/23/2019",
  },
  {
    id: 36,
    title: "Escort",
    desc: "Kentucky Christian College",
    date: "11/21/2019",
  },
  {
    id: 37,
    title: "300ZX",
    desc: "Hokkaido University",
    date: "05/29/2019",
  },
  {
    id: 38,
    title: "Camry",
    desc: "Niigata University of International and Information Studies",
    date: "01/21/2020",
  },
  {
    id: 39,
    title: "Avenger",
    desc: "Minamikyushu University",
    date: "10/17/2019",
  },
  {
    id: 40,
    title: "Thunderbird",
    desc: "University of Central Texas",
    date: "07/07/2019",
  },
  {
    id: 41,
    title: "xA",
    desc: "Deutsch-Ordens Fachhochschule Riedlingen, Hochschule für Wirtschaft",
    date: "05/07/2020",
  },
  {
    id: 42,
    title: "i-350",
    desc: "Kyushu Institute of Design",
    date: "04/13/2020",
  },
  {
    id: 43,
    title: "Durango",
    desc: "Universidad Autónoma de Entre Ríos",
    date: "08/18/2019",
  },
  {
    id: 44,
    title: "G-Series 1500",
    desc: "Shaanxi Normal University",
    date: "06/22/2019",
  },
  {
    id: 45,
    title: "Ram 1500",
    desc: "Universidad de Puerto Rico, Cayey",
    date: "06/11/2019",
  },
  {
    id: 46,
    title: "Sonoma Club Coupe",
    desc: "Faculdades Integradas Toledo",
    date: "12/30/2019",
  },
  {
    id: 47,
    title: "Savana",
    desc: "Fachhochschule Aachen",
    date: "07/26/2019",
  },
  {
    id: 48,
    title: "Mini",
    desc: "Joseph Ayo Babalola University",
    date: "07/26/2019",
  },
  {
    id: 49,
    title: "D150",
    desc: "Hartwick College",
    date: "12/08/2019",
  },
  {
    id: 50,
    title: "5000S",
    desc: "Universidad Nacional de La Matanza",
    date: "06/22/2019",
  },
  {
    id: 51,
    title: "Sportage",
    desc: "University Of Hawaii - System",
    date: "09/17/2019",
  },
  {
    id: 52,
    title: "V40",
    desc: "Guru Jambeshwar University",
    date: "08/25/2019",
  },
  {
    id: 53,
    title: "1 Series",
    desc: "Université du Maine",
    date: "07/10/2019",
  },
  {
    id: 54,
    title: "LS",
    desc: "Hogeschool Antwerpen",
    date: "04/20/2020",
  },
  {
    id: 55,
    title: "Land Cruiser",
    desc: "Technical University of Kielce",
    date: "09/02/2019",
  },
  {
    id: 56,
    title: "Avalon",
    desc: "Robert Morris College",
    date: "04/24/2020",
  },
  {
    id: 57,
    title: "Suburban 2500",
    desc: "Universidad de Alcalá de Henares",
    date: "09/11/2019",
  },
  {
    id: 58,
    title: "tC",
    desc: "Berne University",
    date: "04/25/2020",
  },
  {
    id: 59,
    title: "G-Series 2500",
    desc: "Boston College",
    date: "08/14/2019",
  },
  {
    id: 60,
    title: "Tribeca",
    desc: "Limestone College",
    date: "03/10/2020",
  },
  {
    id: 61,
    title: "Liberty",
    desc: "Charles Sturt University",
    date: "07/22/2019",
  },
  {
    id: 62,
    title: "XT",
    desc: "University College of Gävle",
    date: "04/09/2020",
  },
  {
    id: 63,
    title: "xD",
    desc: "Shendi University",
    date: "02/11/2020",
  },
  {
    id: 64,
    title: "Defender Ice Edition",
    desc: "Mustafa Kemal University",
    date: "08/15/2019",
  },
  {
    id: 65,
    title: "Echo",
    desc: "Schiller International University, London",
    date: "07/11/2019",
  },
  {
    id: 66,
    title: "Rio",
    desc: "Davao Doctors College",
    date: "09/28/2019",
  },
  {
    id: 67,
    title: "Suburban",
    desc: "Schiller International University, Madrid",
    date: "01/24/2020",
  },
  {
    id: 68,
    title: "Cabriolet",
    desc: "Unity College",
    date: "08/10/2019",
  },
  {
    id: 69,
    title: "Forenza",
    desc: "Universidade Santa Cecília dos Bandeirantes",
    date: "03/31/2020",
  },
  {
    id: 70,
    title: "Avalon",
    desc: "University of Art and Design Cluj-Napoca",
    date: "11/15/2019",
  },
  {
    id: 71,
    title: "Santa Fe",
    desc: "Università Pontifcia Salesiana",
    date: "10/18/2019",
  },
  {
    id: 72,
    title: "9-7X",
    desc: "Limestone College",
    date: "08/06/2019",
  },
  {
    id: 73,
    title: "Grand Voyager",
    desc: "United Business Institute",
    date: "05/08/2020",
  },
  {
    id: 74,
    title: "DeVille",
    desc: "Multnomah Bible College",
    date: "06/07/2019",
  },
  {
    id: 75,
    title: "Yukon",
    desc: "Pukyong National University",
    date: "08/08/2019",
  },
  {
    id: 76,
    title: "F-Series",
    desc: "Korea University",
    date: "07/26/2019",
  },
  {
    id: 77,
    title: "Montego",
    desc: "Yunnan Agriculture University",
    date: "08/21/2019",
  },
  {
    id: 78,
    title: "Grand Prix",
    desc:
      "Fachhochschule Konstanz, Hochschule für Technik, Wirtschaft und Gestaltung",
    date: "04/05/2020",
  },
  {
    id: 79,
    title: "Grand Vitara",
    desc: "San Diego State University",
    date: "06/23/2019",
  },
  {
    id: 80,
    title: "M6",
    desc: "Tabor College",
    date: "02/26/2020",
  },
  {
    id: 81,
    title: "RDX",
    desc: "Kyushu Sangyo University",
    date: "12/16/2019",
  },
  {
    id: 82,
    title: "Equinox",
    desc: "Southern Ural State University",
    date: "06/10/2019",
  },
  {
    id: 83,
    title: "Sportage",
    desc: "Kure University",
    date: "11/17/2019",
  },
  {
    id: 84,
    title: "Classic",
    desc: "Fujita Health University",
    date: "12/03/2019",
  },
  {
    id: 85,
    title: "Grand Caravan",
    desc: "Wabash College",
    date: "07/14/2019",
  },
  {
    id: 86,
    title: "FJ Cruiser",
    desc: "Pädagogische Hochschule Zürich (Zurich School of Education)",
    date: "07/05/2019",
  },
  {
    id: 87,
    title: "QX56",
    desc: "Medical Academy in Lodz",
    date: "08/25/2019",
  },
  {
    id: 88,
    title: "Forte",
    desc: "Kendall College",
    date: "08/31/2019",
  },
  {
    id: 89,
    title: "Fiero",
    desc: "Sripatum University",
    date: "02/15/2020",
  },
  {
    id: 90,
    title: "928",
    desc: "Universidad Evangélica de El Salvador",
    date: "11/17/2019",
  },
  {
    id: 91,
    title: "Maxima",
    desc: "Universidad Central del Caribe",
    date: "05/15/2020",
  },
  {
    id: 92,
    title: "Ram 1500",
    desc: "Universitas Tunas Pembangunan",
    date: "05/03/2020",
  },
  {
    id: 93,
    title: "A6",
    desc: "New Mexico Institute of Mining and Technology",
    date: "07/12/2019",
  },
  {
    id: 94,
    title: "Bonneville",
    desc: "Instituto Superior de Línguas e Administração",
    date: "09/29/2019",
  },
  {
    id: 95,
    title: "F150",
    desc: "Loughborough University",
    date: "02/03/2020",
  },
  {
    id: 96,
    title: "Aries",
    desc: "University of Engineering and Technology Lahore",
    date: "05/28/2019",
  },
  {
    id: 97,
    title: "Grand Am",
    desc: "Yorker International University",
    date: "08/07/2019",
  },
  {
    id: 98,
    title: "Mini Cooper",
    desc: "Universidad Pedagógica Nacional, Unidad León",
    date: "08/16/2019",
  },
  {
    id: 99,
    title: "1500 Club Coupe",
    desc: "West Suburban College of Nursing",
    date: "04/29/2020",
  },
  {
    id: 100,
    title: "Liberty",
    desc: "Fachhochschule Braunschweig/Wolfenbüttel",
    date: "12/23/2019",
  },
];
